### ISSUE TITLE
Support for PUT, PATCH, DELETE and cookies

### ISSUE THREAD

**Issue by mna** [cespare/webtest#1]
Hello,

Thanks for this repo, that's a great idea and such a useful package to make public. I added a few features that I wanted in my fork, was wondering if you'd be interested in adding them back in. You can see the list of changes in my README (https://github.com/mna/webtest#readme), but essentially it's what I mention in this issues' title (for cookies, there's `reqcookie` to set a cookie on the request, `cookie` to assert the cookie's value, and `rawcookie` to assert the raw cookie string (i.e. `HttpOnly; Max-Age...`).

Thanks,
Martin

**Comment by cespare** [comment]
Sure, feel free to send a PR.

**Comment by cespare** [comment]
Fixed by #2.
